import { Item } from '../types';

export const SEED_SHOP_ID = 'shop-electrical-01';

export const INITIAL_GADGETS: Omit<Item, 'id' | 'shopId' | 'createdAt' | 'updatedAt'>[] = [
  // Chargers & Adapters
  {
    sku: 'CHG-20W-ANK',
    barcode: '848061023451',
    name: 'Anker 20W USB-C Nano PowerPort Adapter',
    category: 'Chargers & Adapters',
    brand: 'Anker',
    costPrice: 8.50,
    sellingPrice: 15.00,
    quantity: 45,
    reorderLevel: 10,
    supplier: 'Apex Tech Distro',
    description: 'Ultra-compact USB-C fast charger for iPhone and Android devices.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CHG-65W-GAN',
    barcode: '848061023452',
    name: 'Baseus 65W GaN3 Pro Triple Port Fast Charger',
    category: 'Chargers & Adapters',
    brand: 'Baseus',
    costPrice: 22.00,
    sellingPrice: 38.00,
    quantity: 28,
    reorderLevel: 5,
    supplier: 'Apex Tech Distro',
    description: '2x Type-C + 1x USB-A fast charging for laptops, tablets, and phones.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CHG-SAM-25W',
    barcode: '880609054321',
    name: 'Samsung 25W Super Fast Wall Charger (Type-C)',
    category: 'Chargers & Adapters',
    brand: 'Samsung',
    costPrice: 11.00,
    sellingPrice: 20.00,
    quantity: 35,
    reorderLevel: 8,
    supplier: 'ElectroDirect Ltd',
    description: 'Original Super Fast Charging EP-TA800 for Galaxy devices.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CHG-CAR-38W',
    barcode: '693417772301',
    name: 'Ugreen 38W Dual Port Car Fast Charger (PD+QC3.0)',
    category: 'Chargers & Adapters',
    brand: 'Ugreen',
    costPrice: 6.50,
    sellingPrice: 13.00,
    quantity: 18,
    reorderLevel: 5,
    supplier: 'AutoGadgets Global',
    description: 'Metal cigarette lighter adapter with LED ring indicator.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'CHG-WL-15W',
    barcode: '693417772302',
    name: 'Joyroom 15W Qi Magnetic Wireless Charging Pad',
    category: 'Chargers & Adapters',
    brand: 'Joyroom',
    costPrice: 9.00,
    sellingPrice: 18.00,
    quantity: 14,
    reorderLevel: 4,
    supplier: 'Apex Tech Distro',
    description: 'MagSafe compatible slim charging puck with braided cable.',
    archived: false,
    isFavorite: false,
  },

  // Cables
  {
    sku: 'CAB-TC-1M',
    barcode: '693417770101',
    name: 'Braided Type-C to Type-C 60W Cable (1 Meter)',
    category: 'Cables & Leads',
    brand: 'Oraimo',
    costPrice: 2.20,
    sellingPrice: 5.50,
    quantity: 80,
    reorderLevel: 15,
    supplier: 'Transsion Acc Ltd',
    description: 'Heavy duty nylon braided PD charging cord.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CAB-LGT-1M',
    barcode: '693417770102',
    name: 'MFi Certified Lightning to USB-A Cable (1m)',
    category: 'Cables & Leads',
    brand: 'Anker',
    costPrice: 4.50,
    sellingPrice: 10.00,
    quantity: 65,
    reorderLevel: 12,
    supplier: 'Apex Tech Distro',
    description: 'Durable sync & charge lightning cable for iPhone/iPad.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CAB-LGT-TC2M',
    barcode: '693417770103',
    name: 'Type-C to Lightning 20W Fast Charging Cable (2m)',
    category: 'Cables & Leads',
    brand: 'Baseus',
    costPrice: 3.80,
    sellingPrice: 8.50,
    quantity: 40,
    reorderLevel: 10,
    supplier: 'Apex Tech Distro',
    description: 'Extra long 2-meter nylon cord with velcro strap.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'CAB-3IN1-UNIV',
    barcode: '693417770104',
    name: '3-in-1 Universal Cable (Lightning + Type-C + Micro)',
    category: 'Cables & Leads',
    brand: 'Remax',
    costPrice: 3.00,
    sellingPrice: 7.00,
    quantity: 55,
    reorderLevel: 10,
    supplier: 'ElectroDirect Ltd',
    description: 'Multi-port charging wire suitable for any device.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'CAB-HDMI-4K-2M',
    barcode: '693417770105',
    name: 'High-Speed HDMI 2.0 4K Cable 60Hz (2m)',
    category: 'Cables & Leads',
    brand: 'Ugreen',
    costPrice: 4.00,
    sellingPrice: 9.00,
    quantity: 25,
    reorderLevel: 5,
    supplier: 'ElectroDirect Ltd',
    description: 'Gold-plated connectors, braided shielding for TV and consoles.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'CAB-AUX-1M',
    barcode: '693417770106',
    name: '3.5mm Male-to-Male Audio Aux Cable (1.2m)',
    category: 'Cables & Leads',
    brand: 'Vention',
    costPrice: 1.50,
    sellingPrice: 4.00,
    quantity: 32,
    reorderLevel: 6,
    supplier: 'Apex Tech Distro',
    description: 'Oxygen-free copper cable for car audio and speakers.',
    archived: false,
    isFavorite: false,
  },

  // Power Banks & Portable Power
  {
    sku: 'PB-10000-ORA',
    barcode: '489518074901',
    name: 'Oraimo 10,000mAh Toast 10 Ultra-Slim Power Bank',
    category: 'Power Banks',
    brand: 'Oraimo',
    costPrice: 10.50,
    sellingPrice: 20.00,
    quantity: 34,
    reorderLevel: 8,
    supplier: 'Transsion Acc Ltd',
    description: 'Dual output with LED power display and AniFast charging.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'PB-20000-ANK',
    barcode: '489518074902',
    name: 'Anker PowerCore 20,000mAh High Capacity Battery',
    category: 'Power Banks',
    brand: 'Anker',
    costPrice: 26.00,
    sellingPrice: 48.00,
    quantity: 20,
    reorderLevel: 5,
    supplier: 'Apex Tech Distro',
    description: 'Massive capacity battery pack, charges iPhone up to 5 times.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'PB-30000-BAS',
    barcode: '489518074903',
    name: 'Baseus 30,000mAh 65W Power Bank with Digital Display',
    category: 'Power Banks',
    brand: 'Baseus',
    costPrice: 38.00,
    sellingPrice: 68.00,
    quantity: 12,
    reorderLevel: 3,
    supplier: 'Apex Tech Distro',
    description: 'High power bank capable of charging MacBooks and laptops.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'PB-MAG-5000',
    barcode: '489518074904',
    name: 'Magnetic Wireless Power Bank 5,000mAh for MagSafe',
    category: 'Power Banks',
    brand: 'Joyroom',
    costPrice: 14.00,
    sellingPrice: 28.00,
    quantity: 16,
    reorderLevel: 4,
    supplier: 'Apex Tech Distro',
    description: 'Snaps directly to back of phone, slim and lightweight.',
    archived: false,
    isFavorite: false,
  },

  // Extension Sockets & Surge Protectors
  {
    sku: 'EXT-4WAY-2M',
    barcode: '501234567891',
    name: 'Schneider 4-Gang Surge Protected Extension Socket (2m)',
    category: 'Extension Sockets',
    brand: 'Schneider',
    costPrice: 12.00,
    sellingPrice: 22.00,
    quantity: 22,
    reorderLevel: 6,
    supplier: 'VoltMaster Electricals',
    description: 'Heavy duty surge suppression, neon switches per socket.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'EXT-6WAY-USB',
    barcode: '501234567892',
    name: 'Lencent 6-Way Power Strip with 4 USB Ports (3m)',
    category: 'Extension Sockets',
    brand: 'Lencent',
    costPrice: 16.50,
    sellingPrice: 30.00,
    quantity: 19,
    reorderLevel: 5,
    supplier: 'VoltMaster Electricals',
    description: 'Integrated 3.4A smart USB charging hubs and safety shutters.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'EXT-TOWER-12W',
    barcode: '501234567893',
    name: 'Vertical Power Strip Tower 12 Outlets + 5 USB Ports',
    category: 'Extension Sockets',
    brand: 'Huntkey',
    costPrice: 24.00,
    sellingPrice: 45.00,
    quantity: 8,
    reorderLevel: 3,
    supplier: 'VoltMaster Electricals',
    description: 'Space saving vertical surge tower with overload circuit breaker.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'EXT-REEL-25M',
    barcode: '501234567894',
    name: 'Masterplug 25m Heavy Duty Cable Reel 4 Sockets',
    category: 'Extension Sockets',
    brand: 'Masterplug',
    costPrice: 32.00,
    sellingPrice: 58.00,
    quantity: 6,
    reorderLevel: 2,
    supplier: 'VoltMaster Electricals',
    description: 'Industrial drum cable reel with thermal cutout protection.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'EXT-ADPT-MULTI',
    barcode: '501234567895',
    name: 'Universal Multi-Plug Travel Adapter with 2 USB',
    category: 'Extension Sockets',
    brand: 'Brennenstuhl',
    costPrice: 5.00,
    sellingPrice: 11.00,
    quantity: 42,
    reorderLevel: 8,
    supplier: 'VoltMaster Electricals',
    description: 'Converts UK, US, EU, AU plugs with safety fuse.',
    archived: false,
    isFavorite: true,
  },

  // Lighting & Smart Bulbs
  {
    sku: 'BLB-LED-9W-E27',
    barcode: '871869970001',
    name: 'Philips 9W Warm White LED Bulb E27 Screw (Pack of 2)',
    category: 'Lighting & Bulbs',
    brand: 'Philips',
    costPrice: 3.50,
    sellingPrice: 7.50,
    quantity: 50,
    reorderLevel: 12,
    supplier: 'Lumen Electricals',
    description: 'A60 shape, 806 lumens, 15,000 hours rated life.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'BLB-LED-15W-B22',
    barcode: '871869970002',
    name: 'Philips 15W Cool Daylight LED Bulb B22 Bayonet',
    category: 'Lighting & Bulbs',
    brand: 'Philips',
    costPrice: 4.20,
    sellingPrice: 8.50,
    quantity: 36,
    reorderLevel: 8,
    supplier: 'Lumen Electricals',
    description: 'High brightness 1400 lumens energy saving bulb.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'BLB-SMART-RGB',
    barcode: '871869970003',
    name: 'Tuya Smart WiFi RGB+W 10W Bulb (Works with Alexa)',
    category: 'Lighting & Bulbs',
    brand: 'Tuya',
    costPrice: 6.00,
    sellingPrice: 13.00,
    quantity: 24,
    reorderLevel: 5,
    supplier: 'Apex Tech Distro',
    description: '16 Million colors, smartphone app control and voice command.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'BLB-EMERG-12W',
    barcode: '871869970004',
    name: 'Rechargeable Emergency Inverter LED Bulb 12W',
    category: 'Lighting & Bulbs',
    brand: 'Orient',
    costPrice: 5.50,
    sellingPrice: 12.00,
    quantity: 30,
    reorderLevel: 8,
    supplier: 'Lumen Electricals',
    description: 'Built-in lithium battery stays on for 4 hours during power blackout.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'LGT-SOLAR-FL',
    barcode: '871869970005',
    name: 'Solar Flood Light 60W with Motion Sensor & Remote',
    category: 'Lighting & Bulbs',
    brand: 'Solavolt',
    costPrice: 22.00,
    sellingPrice: 42.00,
    quantity: 11,
    reorderLevel: 3,
    supplier: 'Lumen Electricals',
    description: 'IP66 waterproof outdoor security light with solar panel.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'LGT-DESK-LED',
    barcode: '871869970006',
    name: 'Rechargeable Folding LED Desk Lamp with Touch Dimmer',
    category: 'Lighting & Bulbs',
    brand: 'Remax',
    costPrice: 7.50,
    sellingPrice: 16.00,
    quantity: 15,
    reorderLevel: 4,
    supplier: 'ElectroDirect Ltd',
    description: '3 color temperatures, eye protection filter, USB rechargeable.',
    archived: false,
    isFavorite: false,
  },

  // Audio & Earphones
  {
    sku: 'EAR-BT-ORA',
    barcode: '489518074001',
    name: 'Oraimo FreePods 4 Active Noise Cancelling TWS',
    category: 'Audio & Earphones',
    brand: 'Oraimo',
    costPrice: 19.00,
    sellingPrice: 35.00,
    quantity: 26,
    reorderLevel: 6,
    supplier: 'Transsion Acc Ltd',
    description: 'ANC wireless earbuds, transparency mode, 35.5 hour playtime.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'EAR-BT-ANK',
    barcode: '489518074002',
    name: 'Soundcore by Anker Life P2 Mini Wireless Earbuds',
    category: 'Audio & Earphones',
    brand: 'Soundcore',
    costPrice: 21.00,
    sellingPrice: 39.00,
    quantity: 17,
    reorderLevel: 4,
    supplier: 'Apex Tech Distro',
    description: 'Big bass, 3 EQ modes, pocket size case, IPX5 waterproof.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'EAR-WIRE-35MM',
    barcode: '489518074003',
    name: 'JBL C100SI In-Ear Headphones with Microphone (3.5mm)',
    category: 'Audio & Earphones',
    brand: 'JBL',
    costPrice: 5.00,
    sellingPrice: 11.00,
    quantity: 38,
    reorderLevel: 8,
    supplier: 'ElectroDirect Ltd',
    description: 'Signature bass sound, one-button universal inline remote.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'EAR-WIRE-TC',
    barcode: '489518074004',
    name: 'Digital Type-C In-Ear Earphones with DAC Chip',
    category: 'Audio & Earphones',
    brand: 'Samsung',
    costPrice: 6.50,
    sellingPrice: 14.00,
    quantity: 22,
    reorderLevel: 5,
    supplier: 'ElectroDirect Ltd',
    description: 'Direct USB-C digital audio compatible with iPhone 15 & Galaxy.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'SPK-BT-MINI',
    barcode: '489518074005',
    name: 'Zealot S32 Portable Waterproof Bluetooth Speaker 5W',
    category: 'Audio & Earphones',
    brand: 'Zealot',
    costPrice: 9.00,
    sellingPrice: 18.00,
    quantity: 19,
    reorderLevel: 5,
    supplier: 'Apex Tech Distro',
    description: 'Compact cylindrical speaker with TF card, FM radio, and lanyard.',
    archived: false,
    isFavorite: false,
  },

  // Batteries & Power Cells
  {
    sku: 'BAT-AA-4PK',
    barcode: '500039401201',
    name: 'Duracell Ultra Alkaline AA Batteries (Pack of 4)',
    category: 'Batteries & Cells',
    brand: 'Duracell',
    costPrice: 2.80,
    sellingPrice: 5.50,
    quantity: 90,
    reorderLevel: 20,
    supplier: 'VoltMaster Electricals',
    description: 'Long-lasting alkaline power with Powercheck gauge.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'BAT-AAA-4PK',
    barcode: '500039401202',
    name: 'Duracell Ultra Alkaline AAA Batteries (Pack of 4)',
    category: 'Batteries & Cells',
    brand: 'Duracell',
    costPrice: 2.80,
    sellingPrice: 5.50,
    quantity: 75,
    reorderLevel: 15,
    supplier: 'VoltMaster Electricals',
    description: 'Ideal for remotes, toys, thermometers, and medical devices.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'BAT-9V-ENERG',
    barcode: '500039401203',
    name: 'Energizer Max 9V Block Battery (1 Pack)',
    category: 'Batteries & Cells',
    brand: 'Energizer',
    costPrice: 2.20,
    sellingPrice: 4.50,
    quantity: 28,
    reorderLevel: 6,
    supplier: 'VoltMaster Electricals',
    description: 'Reliable power for smoke detectors and digital multimeters.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'BAT-CR2032-5PK',
    barcode: '500039401204',
    name: 'Panasonic CR2032 3V Lithium Coin Cell (5-Pack)',
    category: 'Batteries & Cells',
    brand: 'Panasonic',
    costPrice: 2.00,
    sellingPrice: 4.50,
    quantity: 45,
    reorderLevel: 10,
    supplier: 'VoltMaster Electricals',
    description: 'Standard button cells for car keys, watches, and scales.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'BAT-18650-RECH',
    barcode: '500039401205',
    name: 'Li-ion 18650 3.7V 2600mAh Rechargeable Battery Cell',
    category: 'Batteries & Cells',
    brand: 'Sony/Murata',
    costPrice: 3.50,
    sellingPrice: 7.50,
    quantity: 32,
    reorderLevel: 8,
    supplier: 'ElectroDirect Ltd',
    description: 'High drain cell for rechargeable torches, laser pointers, and vapes.',
    archived: false,
    isFavorite: false,
  },

  // Switches, Sockets & Installation Hardware
  {
    sku: 'SW-1G-1W',
    barcode: '502123400101',
    name: 'MK Logic Plus 1-Gang 1-Way Light Switch (White)',
    category: 'Switches & Sockets',
    brand: 'MK Electric',
    costPrice: 1.80,
    sellingPrice: 4.00,
    quantity: 48,
    reorderLevel: 10,
    supplier: 'VoltMaster Electricals',
    description: 'Antibacterial plate switch with top access screws.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'SW-2G-2W',
    barcode: '502123400102',
    name: 'MK Logic Plus 2-Gang 2-Way Light Switch (White)',
    category: 'Switches & Sockets',
    brand: 'MK Electric',
    costPrice: 2.90,
    sellingPrice: 6.00,
    quantity: 35,
    reorderLevel: 8,
    supplier: 'VoltMaster Electricals',
    description: 'Dual rocker switches for staircase and hallway wiring.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'SCK-13A-DP',
    barcode: '502123400103',
    name: 'British General 13A Double Switched Wall Socket',
    category: 'Switches & Sockets',
    brand: 'BG Electrical',
    costPrice: 3.80,
    sellingPrice: 8.00,
    quantity: 40,
    reorderLevel: 10,
    supplier: 'VoltMaster Electricals',
    description: 'Twin 13A switched outlet socket with dual earth terminals.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'SCK-13A-USB',
    barcode: '502123400104',
    name: 'BG Electrical 13A Double Socket with Integrated USB-A/C',
    category: 'Switches & Sockets',
    brand: 'BG Electrical',
    costPrice: 9.50,
    sellingPrice: 19.00,
    quantity: 20,
    reorderLevel: 5,
    supplier: 'VoltMaster Electricals',
    description: 'Flush wall socket with 3.1A fast USB charging built-in.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'SW-ISO-45A',
    barcode: '502123400105',
    name: '45A DP Cooker / Water Heater Switch with Neon',
    category: 'Switches & Sockets',
    brand: 'Schneider',
    costPrice: 6.00,
    sellingPrice: 13.00,
    quantity: 14,
    reorderLevel: 4,
    supplier: 'VoltMaster Electricals',
    description: 'Heavy appliance isolating switch with red mechanical indicator.',
    archived: false,
    isFavorite: false,
  },

  // Electrical Tools & Testing Gear
  {
    sku: 'TOOL-DMM-PRO',
    barcode: '690123456001',
    name: 'Uni-T UT33D+ Digital Multimeter with NCV Tester',
    category: 'Tools & Testers',
    brand: 'Uni-T',
    costPrice: 11.50,
    sellingPrice: 22.00,
    quantity: 12,
    reorderLevel: 3,
    supplier: 'ToolCraft Pro',
    description: 'Measures AC/DC voltage, DC current, resistance, diode test.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'TOOL-TEST-PEN',
    barcode: '690123456002',
    name: 'Non-Contact AC Voltage Detector Pen (90V-1000V)',
    category: 'Tools & Testers',
    brand: 'Total',
    costPrice: 3.20,
    sellingPrice: 7.00,
    quantity: 25,
    reorderLevel: 6,
    supplier: 'ToolCraft Pro',
    description: 'Audible beeper and flashing red tip for checking live wires.',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'TOOL-STRIP-AUTO',
    barcode: '690123456003',
    name: 'Automatic Wire Stripper and Crimper Tool (8-Inch)',
    category: 'Tools & Testers',
    brand: 'Ingco',
    costPrice: 6.50,
    sellingPrice: 14.00,
    quantity: 16,
    reorderLevel: 4,
    supplier: 'ToolCraft Pro',
    description: 'Self-adjusting jaw for 10-24 AWG wire stripping and cutting.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'TOOL-TAPE-PVC',
    barcode: '690123456004',
    name: 'PVC Electrical Insulation Tape (Pack of 5 Colors)',
    category: 'Tools & Testers',
    brand: '3M / Temflex',
    costPrice: 1.80,
    sellingPrice: 4.00,
    quantity: 60,
    reorderLevel: 15,
    supplier: 'VoltMaster Electricals',
    description: 'Flame retardant electrical tape (Black, Red, Blue, Yellow, Green).',
    archived: false,
    isFavorite: true,
  },
  {
    sku: 'TOOL-SOLD-60W',
    barcode: '690123456005',
    name: 'Adjustable Temperature Soldering Iron Kit 60W',
    category: 'Tools & Testers',
    brand: 'Kaisi',
    costPrice: 8.00,
    sellingPrice: 17.00,
    quantity: 10,
    reorderLevel: 3,
    supplier: 'ToolCraft Pro',
    description: 'Includes 5 interchangeable tips, stand, and solder wire spool.',
    archived: false,
    isFavorite: false,
  },

  // Smart Gadgets & Computer Peripherals
  {
    sku: 'GAD-HUB-TC7',
    barcode: '697123456001',
    name: 'USB-C 7-in-1 Multifunction Hub Adapter (HDMI 4K, SD, USB 3.0)',
    category: 'Smart Gadgets & PC',
    brand: 'Ugreen',
    costPrice: 18.00,
    sellingPrice: 35.00,
    quantity: 14,
    reorderLevel: 4,
    supplier: 'Apex Tech Distro',
    description: 'Aluminum hub with 100W PD pass-through for laptops and tablets.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'GAD-MOUSE-WL',
    barcode: '697123456002',
    name: 'Logitech M185 Wireless Silent Optical Mouse',
    category: 'Smart Gadgets & PC',
    brand: 'Logitech',
    costPrice: 8.50,
    sellingPrice: 16.00,
    quantity: 22,
    reorderLevel: 5,
    supplier: 'ElectroDirect Ltd',
    description: '2.4GHz plug-and-play USB nano receiver, 12-month battery life.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'GAD-WIFI-REP',
    barcode: '697123456003',
    name: 'TP-Link TL-WA850RE 300Mbps Universal Wi-Fi Range Extender',
    category: 'Smart Gadgets & PC',
    brand: 'TP-Link',
    costPrice: 14.00,
    sellingPrice: 26.00,
    quantity: 12,
    reorderLevel: 3,
    supplier: 'ElectroDirect Ltd',
    description: 'Wall-mounted booster with ethernet port and signal strength LEDs.',
    archived: false,
    isFavorite: false,
  },
  {
    sku: 'GAD-SMART-PLUG',
    barcode: '697123456004',
    name: 'Sonoff S26 Smart WiFi Socket with Timer & Power Monitor',
    category: 'Smart Gadgets & PC',
    brand: 'Sonoff',
    costPrice: 7.00,
    sellingPrice: 15.00,
    quantity: 18,
    reorderLevel: 4,
    supplier: 'Apex Tech Distro',
    description: 'App remote control, schedule automation, energy usage tracking.',
    archived: false,
    isFavorite: false,
  },
];
